import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

// Danh sách tất cả các quyền trong hệ thống
export enum Permission {
  // Quản lý lệnh
  ORDER_VIEW = 'ORDER_VIEW',
  ORDER_CREATE = 'ORDER_CREATE',
  ORDER_UPDATE = 'ORDER_UPDATE',
  ORDER_DELETE = 'ORDER_DELETE',
  ORDER_ASSIGN = 'ORDER_ASSIGN',
  ORDER_DETAIL_VIEW = 'ORDER_DETAIL_VIEW',
  
  // Quản lý nhân viên
  EMPLOYEE_VIEW = 'EMPLOYEE_VIEW',
  EMPLOYEE_CREATE = 'EMPLOYEE_CREATE',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  EMPLOYEE_DELETE = 'EMPLOYEE_DELETE',
  EMPLOYEE_DETAIL_VIEW = 'EMPLOYEE_DETAIL_VIEW',
  
  // Quản lý phòng khám
  CLINIC_VIEW = 'CLINIC_VIEW',
  CLINIC_CREATE = 'CLINIC_CREATE',
  CLINIC_UPDATE = 'CLINIC_UPDATE',
  CLINIC_DELETE = 'CLINIC_DELETE',
  CLINIC_DETAIL_VIEW = 'CLINIC_DETAIL_VIEW',
  
  // Quản lý kho
  SUPPLY_VIEW = 'SUPPLY_VIEW',
  SUPPLY_CREATE = 'SUPPLY_CREATE',
  SUPPLY_UPDATE = 'SUPPLY_UPDATE',
  SUPPLY_DELETE = 'SUPPLY_DELETE',
  SUPPLY_DETAIL_VIEW = 'SUPPLY_DETAIL_VIEW',
  ALLOCATION_VIEW = 'ALLOCATION_VIEW',
  ALLOCATION_CREATE = 'ALLOCATION_CREATE',
  ALLOCATION_UPDATE = 'ALLOCATION_UPDATE',
  ALLOCATION_DELETE = 'ALLOCATION_DELETE',
  ALLOCATION_DETAIL_VIEW = 'ALLOCATION_DETAIL_VIEW',
  
  // Quản lý vai trò
  ROLE_VIEW = 'ROLE_VIEW',
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_UPDATE = 'ROLE_UPDATE',
  ROLE_DELETE = 'ROLE_DELETE',
  PERMISSION_VIEW = 'PERMISSION_VIEW',
  PERMISSION_MANAGE = 'PERMISSION_MANAGE',
  
  // Công việc & Trạng thái
  JOB_VIEW = 'JOB_VIEW',
  JOB_CREATE = 'JOB_CREATE',
  JOB_UPDATE = 'JOB_UPDATE',
  JOB_DELETE = 'JOB_DELETE',
  WORK_CONTENT_VIEW = 'WORK_CONTENT_VIEW',
  WORK_CONTENT_CREATE = 'WORK_CONTENT_CREATE',
  WORK_CONTENT_UPDATE = 'WORK_CONTENT_UPDATE',
  WORK_CONTENT_DELETE = 'WORK_CONTENT_DELETE',
  
  // Lịch làm việc
  SCHEDULE_VIEW = 'SCHEDULE_VIEW',
  SCHEDULE_CREATE = 'SCHEDULE_CREATE',
  SCHEDULE_UPDATE = 'SCHEDULE_UPDATE',
  SCHEDULE_DELETE = 'SCHEDULE_DELETE',
  SCHEDULE_ASSIGN = 'SCHEDULE_ASSIGN',
  
  // Thông báo
  NOTIFICATION_VIEW = 'NOTIFICATION_VIEW',
  NOTIFICATION_CREATE = 'NOTIFICATION_CREATE',
  NOTIFICATION_SEND = 'NOTIFICATION_SEND',
  NOTIFICATION_DELETE = 'NOTIFICATION_DELETE',
  
  // Lịch sử
  HISTORY_STATUS_VIEW = 'HISTORY_STATUS_VIEW',
  HISTORY_LOGIN_VIEW = 'HISTORY_LOGIN_VIEW',
  HISTORY_EXPORT = 'HISTORY_EXPORT',
  
  // Báo cáo & Thống kê
  REPORT_VIEW = 'REPORT_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',
  DASHBOARD_VIEW = 'DASHBOARD_VIEW',
  STATISTICS_VIEW = 'STATISTICS_VIEW',
}

@Schema({ timestamps: true })
export class Role extends Document {
  @Prop({ required: true, unique: true })
  tenVaiTro: string;

  @Prop()
  moTa: string;

  @Prop({ type: [String], enum: Permission, default: [] })
  permissions: Permission[];
}

export const RoleSchema = SchemaFactory.createForClass(Role);
